version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=q123
      - POSTGRES_DB=demo
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend

  testdb:
    image: postgres:latest
    container_name: testdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=q123
      - POSTGRES_DB=testdb
    restart: always
    ports:
      - "5432"
    networks:
      - backend

  nats-server:
    image: nats:2.1.9
    container_name: nats-server
    restart: always
    ports:
      - "4222:4222"
    networks:
      - backend

  xm:
    container_name: xm
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8081:8081"
    volumes:
      - xm:/usr/src/xm/
    depends_on:
      - database
      - nats-server
    networks:
      - backend

  tests:
    container_name: tests
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - testdb
      - nats-server
    networks:
      - backend

volumes:
  xm:
  postgres:

networks:
  backend:
    driver: bridge